version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
    networks:
      - appnet

  code-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: code_runner:latest
    command: [ "sleep", "infinity" ]
    networks:
      - appnet

volumes:
  rabbitmq_data:

networks:
  appnet:
    driver: bridge
