[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = [
  "E203",
  "W503",
]
exclude = [
  ".git",
  "__pycache__",
  "migrations",
  ".venv",
  "build",
  "dist",
]
per-file-ignores = [
  "__init__.py:F401",
]

[tool.mypy]
python_version = "3.11"
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
files = ["manage.py", "config", "apps", "common", "api"]
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_return_any = true
strict_optional = true
follow_imports = "normal"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings.base"
